<?php

 /**
   * page_attachments_alter_hook
   */
function fast_buttons_page_attachments_alter(array &$attachments) {

		$path=\Drupal::service('path.current')->getPath();
		
		if($path == '/admin/modules' || $path == '/admin/modules/uninstall' ){
			$path=\Drupal::service('path.current')->getPath();
			$config = \Drupal::config('fast_buttons.settings');
    		$def_display = $config->get('displayOption');
    		$def_flush = $config->get('flushOption');
    		if ($def_display == 'simple' ){
    			if($def_flush == true ){
    				$attachments['#attached']['library'][] = 'fast_buttons/fast_buttons';
					$attachments['#attached']['library'][] = 'fast_buttons/fast_buttons_flush';
    			}else
    				$attachments['#attached']['library'][] = 'fast_buttons/fast_buttons';	
			}
			if ($def_display == 'sticky' ){
				if($def_flush == true ){
    				$attachments['#attached']['library'][] = 'fast_buttons/fast_buttons_extensive';
					$attachments['#attached']['library'][] = 'fast_buttons/fast_buttons_flush_extensive';
    			}else
    				$attachments['#attached']['library'][] = 'fast_buttons/fast_buttons_extensive';
			}

	}
	}